HotelReservations/Areas/HotelAdministration/Models/HotelViewModel.cs
using HotelReservations.Data.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HotelReservations.Web.Areas.HotelAdministration.Models
{
    public class HotelViewModel
    {
        public HotelViewModel()
        {

        }

        public HotelViewModel(Hotel hotel)
        {
            if (hotel != null)
            {
                this.Id = hotel.Id;
                this.Name = hotel.Name;
                this.Stars = hotel.Stars;
                this.Address = hotel.Address;
                this.CityName = hotel.City.Name;
                this.CountryName = hotel.Country.Name;
                this.Zip = hotel.Zip;
                this.Rooms = new HashSet<RoomViewModel>();
                hotel.Rooms.Select(x => this.Rooms.Add(new RoomViewModel(x)));
                this.PhotoUrls = new HashSet<string>();
                bool hotelPhotosEmpty = hotel.PhotoUrls != null && this.PhotoUrls.Count > 0;

                if (!hotelPhotosEmpty)
                {
                    hotel.PhotoUrls.Select(x => this.PhotoUrls.Add(x.Url));
                }

                bool firstPhotoEmpty = hotel.FirstPhotoUrl == null || hotel.FirstPhotoUrl == String.Empty;

                if (!firstPhotoEmpty)
                {
                    this.FirstPhotoUrl = hotel.FirstPhotoUrl;   //this.PhotoUrls.ElementAt<string>(0);
                }
                //else if (this.FirstPhotoUrl!=null)
                //{
                //    this.FirstPhotoUrl = hotel.FirstPhotoUrl;
                //}

                this.HasParking = hotel.HasParking;
                this.HasInternet = hotel.HasInternet;
                this.HasRestaurant = hotel.HasRestaurant;

            }
        }
        [ScaffoldColumn(false)]
        public Guid Id { get; private set; }

        [Required]
        [MinLength(2)]
        public string Name { get; set; }

        [Required]
        [Range(1, 5)]
        public short Stars { get; set; }

        public string Address { get; set; }

        [Required]
        [MinLength(2)]
        public string CityName { get; set; }

        [MinLength(2)]
        [MaxLength(10)]
        public string Zip { get; set; }

        [Required]
        [MinLength(2)]
        public string CountryName { get; set; }

        public HashSet<RoomViewModel> Rooms { get; set; }

        public HashSet<string> PhotoUrls { get; set; }

        public string FirstPhotoUrl { get; set; }

        public bool HasParking { get; set; }

        public bool HasRestaurant { get; set; }

        public bool HasInternet { get; set; }

        [ScaffoldColumn(false)]
        public string UserId { get; set; }

        public Hotel CreateHotel()
        {
            var result = new Hotel();
            result.Name = this.Name;
            result.Stars = this.Stars;
            result.Address = this.Address;
            result.City = new City();
            result.City.Name = this.CityName;
            result.Country = new Country();
            result.Country.Name = this.CountryName;
            result.Zip = this.Zip;
            result.Rooms = new HashSet<Room>();
            // TODO: to fix rooms
            result.PhotoUrls = new HashSet<PhotoUrl>();
            bool photosEmpty = this.PhotoUrls == null || this.PhotoUrls.Count == 0;
            bool firstPhotoEmpty = this.FirstPhotoUrl == null || this.FirstPhotoUrl == String.Empty;

            if (!photosEmpty)
            {
                foreach (var photo in this.PhotoUrls)
                {
                    var photoUrl = new PhotoUrl();
                    photoUrl.Url = photo;
                    result.PhotoUrls.Add(photoUrl);
                }
            }
            result.FirstPhotoUrl = this.FirstPhotoUrl;  //TODO!

            result.HasInternet = this.HasInternet;
            result.HasParking = this.HasParking;
            result.HasRestaurant = this.HasRestaurant;
            result.User = new User();
            result.User.Id = this.UserId;

            return result;
        }
    }
}

HotelReservations/Areas/HotelAdministration/Models/HotelsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelReservations.Web.Areas.HotelAdministration.Models
{
    public class HotelsOfUserViewModel
    {
        public IEnumerable<HotelViewModel> Hotels { get; set; }
    }
}

HotelReservations/Models/HotelsViewModel.cs
using HotelReservations.Data.Model;
using HotelReservations.Web.Areas.HotelAdministration.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HotelReservations.Web.Models
{
    public class HotelsViewModel
    {
        //public HotelsViewModel()
        //{
        //    this.Collection = new List<HotelsViewModel>();
        //}


        public ICollection<HotelViewModel> Collection { get; set; }
    }
}

HotelReservations/Areas/HotelAdministration/Controllers/HotelController.cs
using Bytes2you.Validation;
using HotelReservations.Infrastructure;
using HotelReservations.Services.Contracts;
using HotelReservations.Web.Areas.HotelAdministration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelReservations.Web.Areas.HotelAdministration.Controllers
{
    [Authorize(Roles = WebConstants.HotelAdminRoleString)]
    public class HotelController : Controller
    {
        private readonly IHotelsService hotelsService;
        private readonly IUserService userService;

        public HotelController(IHotelsService hotelsService, IUserService userService)
        {
            Guard.WhenArgument(hotelsService, "hotelsService").IsNull().Throw();
            Guard.WhenArgument(userService, "userService").IsNull().Throw();
            this.hotelsService = hotelsService;
            this.userService = userService;
        }

        // GET: HotelAdministration/Hotel
        public ActionResult Index()
        {
            var user = User.Identity;
            var dbUser = this.userService.GetByUserName(user.Name);

            var hotelsOfUser = this.hotelsService
                .GetAll()
                .Where(hotel => hotel.User.Id == dbUser.Id)
                .ToList()
                .Select(h => new HotelViewModel(h));

            var hotelsViewModel = new HotelsOfUserViewModel();
            hotelsViewModel.Hotels= hotelsOfUser;

            return View(hotelsViewModel);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(HotelViewModel hotel)
        {
            var user = User.Identity;
            var dbUser = this.userService.GetByUserName(user.Name);
            hotel.UserId = dbUser.Id;

            this.hotelsService.Add(hotel.CreateHotel());
            return RedirectToAction("Index");
        }

    }
}

HotelReservations/Controllers/HotelsController.cs
using HotelReservations.Services.Contracts;
using HotelReservations.Web.Models;
using HotelReservations.Web.Areas.HotelAdministration.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System;
using HotelReservations.Data.Model;

namespace HotelReservations.Web.Controllers
{
    public class HotelsController : Controller
    {
        private IHotelsService hotelsService;

        public HotelsController(IHotelsService hotelsService)
        {
            this.hotelsService = hotelsService;
        }

        // GET: Hotels
        [HttpGet]
        public ActionResult Index()
        {
            var hotels = new HotelsViewModel();
            hotels.Collection = new List<HotelViewModel>();

            var dbHotels = this.hotelsService
                .GetAll()
                //.Select(x => new HotelViewModel(x))
                .ToList();

            foreach (var dbHotel in dbHotels)
            {
                var hotel = new HotelViewModel(dbHotel);
                hotels.Collection.Add(hotel);
            }

            return View(hotels.Collection);
        }

        public ActionResult Details(Guid? id)
        {
            Hotel hotel = this.hotelsService.GetById(id);

            HotelViewModel viewModel = new HotelViewModel(hotel);

            return this.View(viewModel);
        }

    }
}

HotelReservations/Views/Hotels/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using HotelReservations.Web.Areas.HotelAdministration.Models

@model HotelViewModel

<h2>@Model.Name</h2>

<div class="panel panel-default">
    <div class="panel-body">
        <img class="img-rounded" src=@Model.FirstPhotoUrl />
        <p></p>
        <p>
            @for (int i = 1; i <= Model.Stars; i++)
            {
                <span class="glyphicon glyphicon-star-empty"></span>
            }
        </p>
        <p>Address: @Model.Address</p>
        <p>City: @Model.CityName Zip: @Model.Zip</p>
        <p>Country: @Model.CountryName</p>
        <ul>
            @if (Model.HasRestaurant)
            {
                <li>Restaurant</li>
            }
            @if (Model.HasParking)
            {
                <li>Parking</li>
            }
            @if (Model.HasInternet)
            {
                <li>Internet</li>
            }

        </ul>
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink("Reservation", "Add", "Reservation", new { Model.Id }, new { @class = "btn btn-info" });
            @*<button class="btn btn-info" formaction="">Reservation</button>*@
        }
    </div>
</div>

HotelReservations/Views/Hotels/Index.cshtml
@using HotelReservations.Web.Models
@using HotelReservations.Web.Areas.HotelAdministration.Models
@using System.Collections.Generic
@*@using Kendo.Mvc.resources*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model ICollection<HotelViewModel>

<h2>Select a hotel</h2>

@for (int i = 0; i <= Model.Count / 6; i++)
{
    <div class="row">
        @for (int j = 0; j < 6; j++)
        {
            if (i * 6 + j >= Model.Count)
            {
                break;
            }
            <div class="col-sm-2">
                <div class="thumbnail">
                    <img src="@Model.ElementAt(i*6+j).FirstPhotoUrl" alt="@Model.ElementAt(i*6+j).Name" />
                    @*@Html.ActionLink(Model.ElementAt(i*6+j).Name, "Details", "Hotels", new { id = "Model.ElementAt(i*6+j).Id" })*@
                    <a href="/Hotels/Details/@Model.ElementAt(i*6+j).Id">
                        <h4>@Model.ElementAt(i * 6 + j).Name</h4>
                    </a>
                    <p>
                        @for (int s = 0; s < @Model.ElementAt(i * 6 + j).Stars; s++)
                        {
                            <span class="glyphicon glyphicon-star-empty"></span>
                        }
                    </p>
                    <p>City: @Model.ElementAt(i * 6 + j).CityName</p>
                    <p>Country: @Model.ElementAt(i * 6 + j).CountryName</p>
                </div>
            </div>
        }

    </div>

}

@*Kendo below*@


@*@{string url = ""; }*@
@*<script type="text/x-kendo-tmpl" id="template">
    <div class="product">
        <a href="/Hotels/Details/#:Id#">
            <img src="#:FirstPhotoUrl#" alt="#:FirstPhotoUrl# image" />
        </a>*@
@*@Html.ActionLink("#:Name#", "Details", "Hotels", new { id = "#:Id#" })*@
@*<a href="/Hotels/Details/#:Id#">
        <h3>#:Name#</h3>
    </a>*@
@*@{string starsStr = "#:stars#";}
    @{ int stars = int.Parse(starsStr); }*@
@*<p>Category: #:Stars#-stars</p>*@
@*<p>
        @{for (int i = 1; i <= stars; i++)
            {
                <span class="glyphicon glyphicon-star-empty"></span>
            }
        }
    </p>*@
@*<p>#:CityName#</p>
    <p>#:CountryName#</p>*@
@*<p>#:kendo.toString(Name, "c")#</p>*@
@*</div>
    </script>*@

@*<div class="demo-section k-content wide">
        @(Html.Kendo().ListView<HotelViewModel>(Model)
        .Name("listView")
        .TagName("div")
        .ClientTemplateId("template")
        .DataSource(dataSource => dataSource
            .PageSize(20)
            .ServerOperation(false)
         )
        .Pageable()
        //.ToolBar(toolbar => toolbar.Create())
        .Selectable(selectable => selectable.Mode(ListViewSelectionMode.Single))
        )
    </div>*@

@*<style>
        #listView {
            padding: 10px 5px;
            margin-bottom: -1px;
            min-height: 510px;
            /* Avoid cutout if font or line is bigger */
            font: inherit;
        }

        .product {
            float: left;
            position: relative;
            width: 111px;
            height: 200px;
            margin: 0 5px;
            padding: 0;
            border: 1px solid lightgrey;
            border-radius: 5px;
        }

            .product img {
                width: 110px;
                height: 110px;
            }

            .product h3 {
                margin: 0;
                padding: 3px 5px 0 0;
                max-width: 96px;
                overflow: hidden;
                line-height: 1.0em;
                font-size: .9em;
                font-weight: normal;
                text-transform: uppercase;
                color: #999;
                text-align: center;
            }

            .product p {
                font-size: .7em;
                color: #999;
                text-align: center;
                /*visibility: hidden;*/
            }

            .product:hover p {
                visibility: visible;
                position: absolute;
                width: 110px;
                height: 110px;
                top: 0;
                margin: 0;
                padding: 0;
                line-height: 110px;
                vertical-align: middle;
                text-align: center;
                color: #fff;
                background-color: rgba(0,0,0,0.75);
                transition: background .2s linear, color .2s linear;
                -moz-transition: background .2s linear, color .2s linear;
                -webkit-transition: background .2s linear, color .2s linear;
                -o-transition: background .2s linear, color .2s linear;
            }

        .k-listview:after {
            content: ".";
            display: block;
            height: 0;
            clear: both;
            visibility: hidden;
        }
    </style>*@