HotelReservations/Areas/HotelAdministration/Controllers/HotelController.cs
using Bytes2you.Validation;
using HotelReservations.Infrastructure;
using HotelReservations.Services.Contracts;
using HotelReservations.Web.Areas.HotelAdministration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelReservations.Web.Areas.HotelAdministration.Controllers
{
    [Authorize(Roles = WebConstants.HotelAdminRoleString)]
    public class HotelController : Controller
    {
        private readonly IHotelsService hotelsService;
        private readonly IUserService userService;

        public HotelController(IHotelsService hotelsService, IUserService userService)
        {
            Guard.WhenArgument(hotelsService, "hotelsService").IsNull().Throw();
            Guard.WhenArgument(userService, "userService").IsNull().Throw();
            this.hotelsService = hotelsService;
            this.userService = userService;
        }

        // GET: HotelAdministration/Hotel
        public ActionResult Index()
        {
            var user = User.Identity;
            var dbUser = this.userService.GetByUserName(user.Name);

            var hotelsOfUser = this.hotelsService
                .GetAll()
                .Where(hotel => hotel.User.Id == dbUser.Id)
                .ToList()
                .Select(h => new HotelViewModel(h));

            var hotelsViewModel = new HotelsOfUserViewModel();
            hotelsViewModel.Hotels= hotelsOfUser;

            return View(hotelsViewModel);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(HotelViewModel hotel)
        {
            var user = User.Identity;
            var dbUser = this.userService.GetByUserName(user.Name);
            hotel.UserId = dbUser.Id;

            this.hotelsService.Add(hotel.CreateHotel());
            return RedirectToAction("Index");
        }

    }
}

HotelReservations/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using HotelReservations.Infrastructure
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - On-line Hotel Reservations</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/kendo")*@
    @Scripts.Render("~/bundles/jqueryui")

    @*<link href="https://kendo.cdn.telerik.com/2017.3.913/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2017.3.913/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2017.3.913/styles/kendo.default.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2017.3.913/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.913/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.913/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.913/js/kendo.aspnetmvc.min.js"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Reservations", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", new { area = string.Empty, controller = "Home" })</li>
                    <li>@Html.ActionLink("Hotel List", "Index", new { area = string.Empty, controller = "Hotels" })</li>
                    <li>@Html.ActionLink("About", "About", new { area = string.Empty, controller = "Home" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", new { area = string.Empty, controller = "Home" })</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Reservations", "MyReservations", new { area = string.Empty, controller = "Reservation" })</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole(WebConstants.SiteAdminRoleString))
                    {
                        <li>@Html.ActionLink("SiteAdmin", "Index", "SiteAdmin", new { area = "SiteAdministration" }, new { })</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole(WebConstants.HotelAdminRoleString))
                    {
                        <li>@Html.ActionLink("HotelAdmin", "Index", "Hotel", new { area = "HotelAdministration" }, new { })</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hotel Reservations</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>